# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Construct_W0 <- function(sigma2, lambda) {
    .Call('_FastGaSP_Construct_W0', PACKAGE = 'FastGaSP', sigma2, lambda)
}

Construct_G <- function(delta_x, lambda) {
    .Call('_FastGaSP_Construct_G', PACKAGE = 'FastGaSP', delta_x, lambda)
}

Construct_W <- function(sigma2, delta_x, lambda, W0) {
    .Call('_FastGaSP_Construct_W', PACKAGE = 'FastGaSP', sigma2, delta_x, lambda, W0)
}

Get_Q_K <- function(GG, W, C0, VV) {
    .Call('_FastGaSP_Get_Q_K', PACKAGE = 'FastGaSP', GG, W, C0, VV)
}

Get_log_det_S2 <- function(param, have_noise, delta_x, output) {
    .Call('_FastGaSP_Get_log_det_S2', PACKAGE = 'FastGaSP', param, have_noise, delta_x, output)
}

Get_C_R_K_pred <- function(index, GG, W, C0, VV) {
    .Call('_FastGaSP_Get_C_R_K_pred', PACKAGE = 'FastGaSP', index, GG, W, C0, VV)
}

Get_m_a_pred <- function(index, output_vec, GG, K) {
    .Call('_FastGaSP_Get_m_a_pred', PACKAGE = 'FastGaSP', index, output_vec, GG, K)
}

Get_S_KK <- function(index, GG, C, R) {
    .Call('_FastGaSP_Get_S_KK', PACKAGE = 'FastGaSP', index, GG, C, R)
}

Get_s_1st <- function(m, a, C, KK) {
    .Call('_FastGaSP_Get_s_1st', PACKAGE = 'FastGaSP', m, a, C, KK)
}

Kalman_smoother <- function(param, have_noise, index_obs, delta_x_all, output, sigma_2_hat) {
    .Call('_FastGaSP_Kalman_smoother', PACKAGE = 'FastGaSP', param, have_noise, index_obs, delta_x_all, output, sigma_2_hat)
}

